### Get all contacts
GET http://localhost:3000/users

### Get a single contact (Replace {id} with an actual ID)
GET http://localhost:3000/contacts/67e727e5543876dfb9701b78

### Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "favoriteColor": "Blue",
  "birthday": "2000-01-01"
}

### Update a contact (Replace {id} with an actual ID)
PUT http://localhost:3000/contacts/67e727e5543876dfb9701b78
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "janedoe@example.com",
  "favoriteColor": "Red",
  "birthday": "1999-12-31"
}

### Delete a contact (Replace {id} with an actual ID)
DELETE http://localhost:3000/contacts/67e727e5543876dfb9701b79