// Example Swagger documentation for OAuth routes
const swaggerDefinition = {
  openapi: '3.0.0',
  info: {
    title: 'Your API',
    version: '1.0.0',
    description: 'API documentation for the OAuth authentication system.',
  },
  paths: {
    '/auth/google': {
      get: {
        summary: 'Initiates Google OAuth login',
        responses: {
          302: {
            description: 'Redirects to Google login',
          },
        },
      },
    },
    '/auth/google/callback': {
      get: {
        summary: 'Handles Google OAuth callback',
        responses: {
          302: {
            description: 'Redirects to protected route after successful login',
          },
        },
      },
    },
    '/auth/logout': {
      get: {
        summary: 'Logs the user out',
        responses: {
          200: {
            description: 'Logs the user out and redirects to homepage',
          },
        },
      },
    },
    '/protected': {
      get: {
        summary: 'Protected route that requires authentication',
        responses: {
          200: {
            description: 'Returns content only accessible to authenticated users',
          },
        },
      },
    },
  },
};

module.exports = swaggerDefinition;
